// <auto-generated />
using System;
using LS.Core.Data.SQLDataConnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LS.Core.Data.Migrations
{
    [DbContext(typeof(StudentDataBase))]
    partial class StudentDataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LS.Core.Data.Entity.Class", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CLASSNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GUID");

                    b.ToTable("CLASS");
                });

            modelBuilder.Entity("LS.Core.Data.Entity.Student", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("STUAGE")
                        .HasColumnType("int");

                    b.Property<string>("STUCLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUSEX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GUID");

                    b.ToTable("STUDENT");
                });

            modelBuilder.Entity("LS.Core.Data.Entity.Teacher", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CLASSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TEACHERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GUID");

                    b.ToTable("TEACHER");
                });
#pragma warning restore 612, 618
        }
    }
}
